### ISSUE TITLE
Some accounts cant load from new MatrixSdkDatabase

### ISSUE THREAD

**Issue by Airyzz** [famedly/matrix-dart-sdk#1642]
### Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions.
- [ ] I already asked for help in the chat

### In which Project did the bug appear?

Other

### If you selected \"Other\" as Project, please enter in which project the bug occurred.

matrix-dart-sdk

### On which platform did the bug appear?

Android

### SDK Version

0.24.1

### Describe the problem caused by this bug

I was testing the new database, and for two of my testing accounts it's working flawlessly, but when attempting to use my main account, I get an error when loading from DB

Initial impression is that the account data is too large and is breaking db. So far I have only been able to reproduce this on Android, both on my physical device and on an emulator. Linux seems to be working fine.

Maybe there is an issue in my implementation, but I'm not sure.
For reference my implementation is [here](https://github.com/commetchat/commet/blob/3b5551a3fc4e3fc2401785300620b84cbbbf8a2f/commet/lib/client/matrix/matrix_client.dart#L244)

### Steps To Reproduce

1. Log in with large account (not 100% sure what exactly in the account data is causing the problem at this point)
2. Close app
3. Reopen app to load from database
4. Error occurs

### Screenshots or Logs

```
DatabaseException(Row too big to fit into CursorWindow requiredPos=46, totalRows=47) sql 'SELECT * FROM box_room_account_data' args []

#0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11)
<asynchronous suspension>
#1      SqfliteDatabaseMixin.txnRawQuery.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:575)
<asynchronous suspension>
#2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33)
<asynchronous suspension>
#3      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:506)
<asynchronous suspension>
#4      Box.getAllValues (package:matrix/src/database/sqflite_box.dart:145)
<asynchronous suspension>
#5      MatrixSdkDatabase.getRoomList.<anonymous closure> (package:matrix/src/database/matrix_sdk_database.dart:579)
<asynchronous suspension>
#6      Client.init (package:matrix/src/client.dart:1578)
<asynchronous suspension>
```

**Comment by krille-chan** [comment]
Thank you very much for your report. Unfortunately I cannot reproduce it yet. Can you give me more information? Which client are you using? Can you maybe try to dump the row which appears to be too large so we can see how this could happened?

**Comment by Airyzz** [comment]
I dumped the database, and it seems the problem is that there is 7mb of json data (317232 lines) in `com.famedly.receipts_state` for the room `#matrix:matrix.org`

Maybe my implementation for handling this data is incorrect, but didn't seem to have any issues with hive db so I'm not sure

**Comment by krille-chan** [comment]
Ah thank you. That's very helpful. I will take a look if we can optimize something there

**Comment by krille-chan** [comment]
Okay so looks like we can fix this by storing the read receipts different. @nico-famedly any ideas? Maybe it makes not much sense to store all receipts in such big rooms and instead store only a subset and a counter for receipts?

**Comment by nico-famedly** [comment]
Well, we can't query receipts from the server at a later point, so if we want to show the read receipts for a past message, we almost always have to store all of them, I think. However we wanted to store the receipts individually instead of in one big json thingy for quite some time, iirc.

**Comment by krille-chan** [comment]
> However we wanted to store the receipts individually instead of in one big json thingy for quite some time, iirc.

Well that's really pain in the ass. We would not only need to change the matrix sdk database but all other databases too and how the SDK handles read receipts in multiple places. This refactoring can take a long time

**Comment by krille-chan** [comment]
@Airyzz I have tried to reproduce your problem by joining #matrix:matrix.org with a test account and then reload the app. Was tested on Android 14 in an Emulator but it worked fine for me. Do you have more information for us? Which app are you using on what kind of device and operating system? How long have you been in this room? Have you tried to logout and login again?

**Comment by Airyzz** [comment]
I made a minimum reproduction of the issue: https://gist.github.com/Airyzz/60ab91fe01d3c662dabcb664c5339091

Running this on a Android Emulator (Android API 34, x86_64) and logging in to my main account and restarting the app causes the same error. Logging out and logging in has no effect, as this bug happens every time I log in. my main account has been in this room for probably well over 5 months, but I also tested a dev account which only joined today and it also produced the same issue.

I am also attaching a video showing the bug in action: 

https://github.com/famedly/matrix-dart-sdk/assets/36567925/80f1e49f-d0c2-4f96-8012-bf4ba8415387

**Comment by krille-chan** [comment]
Thank you so much. I have a possible workaround here: https://github.com/famedly/matrix-dart-sdk/pull/1652 do you think you can try this out with your account and see if it works then or throws a different error? That might be the best solution for now until we can refactor the whole SDK to store the receipts in a different way

**Comment by Airyzz** [comment]
Tested it out now, getting a different error:

```
E/SQLiteQuery( 5468): exception: Row too big to fit into CursorWindow requiredPos=29, totalRows=30; query: SELECT * FROM box_room_account_data
I/flutter ( 5468): [Matrix] Box.getAllValues() failed. Try to half the amount of data - DatabaseException(Row too big to fit into CursorWindow requiredPos=29, totalRows=30) sql 'SELECT * FROM box_room_account_data' args []
E/SQLiteLog( 5468): (1) near "?": syntax error in "SELECT COUNT(*) FROM ?"
I/flutter ( 5468): [Matrix] Initialization failed - DatabaseException(near "?": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT COUNT(*) FROM ?) sql 'SELECT COUNT(*) FROM ?' args [box_room_account_data]
```

If i understand the code correctly, the idea is to get half the amount of entries? I'm not sure if this will work, as I dont think the issue is with the total number of entries, but its that one single entry is larger than cursor size. If this large entry is still part of the half that is read, then surely there will still be an issue?

If you are still having problems reproducing the error, I can maybe share the database with you privately if that will help

**Comment by krille-chan** [comment]
Thank you very much. The error looks like I messed up the COUNT(*) syntax but anyway my approach seems to be incorrect. Okay, let's try a different workaround. In the same PR I have added a value `maxStoreReadReceiptsPerRoom` to the Client object and set it to 100 by default. It can be changed to any value in the Client constructor. Can you try out if this fixes your problem? The workaround is not nice as it stops storing read receipts of other users after a certain amount of data but it should for now make it possible to use the app again:

https://github.com/famedly/matrix-dart-sdk/pull/1652

**Comment by Airyzz** [comment]
this seems to be working! Thank you for your promptness in this issue :)

could you clarify for me, does this workaround stop storing read receipts entirely once it hits 100, or does it store the most recent 100 read receipts? And what impact will this have on read receipt functionality?

**Comment by krille-chan** [comment]
> this seems to be working! Thank you for your promptness in this issue :)
> 
> could you clarify for me, does this workaround stop storing read receipts entirely once it hits 100, or does it store the most recent 100 read receipts? And what impact will this have on read receipt functionality?

So this stops storing further read receipts if there are more than 100. While own read receipts are still always stored. The receipts are still shown in the GUI in the same session when they come down the sync but they will be lost after restarting the app. It is a vey ugly workaround but at least it makes the app usable for now. The fix would require a huge database structure change which I would like to do, once we have reduced the amount of databases and have something like queries implemented

**Comment by krille-chan** [comment]
I was able to reproduce the problem now on Android using this code snipped:

```dart
String createLargeString(String character, int desiredSize) {
  final buffer = StringBuffer();

  while (buffer.length < desiredSize) {
    buffer.write(character);
  }

  return buffer.toString();
}


final hugeDataObject = {'foo': createLargeString('A', 5 * 1024 * 1024)};

await database.storeAccountData(
          'm.huge_data_test',
          jsonEncode(hugeDataObject),
);

// Throws the cursorwindow error
final events = await database.getAccountData();
```
So I just throw 5MB into the database and then read it.
I tested it with different sqlite libraries and the problem only occurs when using the latest version of sqflite. With sqlcipher everything worked fine. Same with sqlite3 over ffi on Android (which is used by the drift package). So the fix is relatively easy. You can either use sqlcipher instead of sqflite (uses a different library on Android) or use [sqlite3 over ffi ](https://pub.dev/packages/sqlite3_flutter_libs).

So instead of:

```dart
MatrixSdkDatabase(
  client.clientName,
  database: await openDatabase('path...'),
);
```

You could use:

```dart
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

MatrixSdkDatabase(
  client.clientName,
  database: await databaseFactoryFfi.openDatabase('path...'),
  sqfliteFactory: databaseFactoryFfi,
);
```

I will also test how this behaves on iOS and then provide a PR which mentions this in the documentation

**Comment by Airyzz** [comment]
Thank you, this has worked beautifully!

**Comment by krille-chan** [comment]
Edit: I can confirm that this does **not** happen on iOS for any database. So I will mark this as fixed once the documentation is done

**Comment by krille-chan** [comment]
Added a comment in the docs about this problem so we see this as fixed
