### ISSUE TITLE
#63 ⁃ error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT

### ISSUE THREAD

**Issue by famedly-bot** [famedly/matrix-dart-sdk#247]
In GitLab by @yswtrue on Nov 12, 2021, 08:59

```
# [ERROR] Capture exception - PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
	at com.android.org.conscrypt.OpenSSLEvpCipher.doFinalInternal(OpenSSLEvpCipher.java:152)
	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
	at e.m.a.b.b.a(StorageCipher18Implementation.java:7)
	at e.m.a.a.i(FlutterSecureStoragePlugin.java:2)
	at e.m.a.a.e(FlutterSecureStoragePlugin.java:2)
	at e.m.a.a$b.run(FlutterSecureStoragePlugin.java:14)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.os.HandlerThread.run(HandlerThread.java:67)
, null)

## Stacktrace:

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
<asynchronous suspension>
#2      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:50)
<asynchronous suspension>
#3      FlutterSecureStorage.containsKey (package:flutter_secure_storage/flutter_secure_storage.dart:71)
<asynchronous suspension>
#4      FlutterMatrixHiveStore.hiveDatabaseBuilder (package:chat_frontend/fluffychat/utils/matrix_sdk_extensions.dart/flutter_matrix_hive_database.dart:66)
<asynchronous suspension>
#5      Client.init (package:matrix/src/client.dart:912)
<asynchronous suspension>
#6      MatrixState._initWithStore (package:chat_frontend/fluffychat/widgets/matrix.dart:81)
<asynchronous suspension>

```

dependencies:   matrix: ^0.6.2

# DoR Bug report
- [x] The issue title and description should be explained in English language.
- [ ] Description of current and expected behavior is understood.
- [ ] If necessary,  reproduction steps should be included.
- [x] Every attached media (if applicable) includes a short description.
- [ ] Bug can be reproduced in the latest development version
- [ ] Severity is understood.
- [x] Responsible squad has been identified (issue is labeled)
- [ ] There is a list of affected components if needed.
- [ ] There is an estimate on the effort to fix the bug.

**Comment by krille-chan** [comment]
Would close this because of inactivity now. I also haven't seen this anywhere and there is also no sentry report about it
